from uuid import uuid4

from app.application.schemas.session import (
    SessionAdvanceRequest,
    SessionCreateRequest,
    SessionResponse,
)
from app.domain.models.session import FocusArea, ResearchCycleStage, ResearchSession
from app.domain.services.prioritization import PrioritizationService
from app.infrastructure.repositories.session_repository import InMemorySessionRepository


class OrchestrationService:
    def __init__(self) -> None:
        self.repository = InMemorySessionRepository()
        self.prioritization_service = PrioritizationService()

    def create_session(self, payload: SessionCreateRequest) -> SessionResponse:
        session = ResearchSession(
            session_id=str(uuid4()),
            teacher_id=payload.teacher_id,
            project_title=payload.project_title,
            cycle_stage=ResearchCycleStage.PLANNING,
            current_focus=FocusArea.RESEARCH_PROBLEM,
            guiding_questions=self.prioritization_service.default_questions(
                FocusArea.RESEARCH_PROBLEM
            ),
            latest_draft=None,
            state_snapshot={"context_note": payload.context_note or ""},
        )
        self.repository.save(session)
        return SessionResponse.model_validate(session.to_dict())

    def get_session(self, session_id: str) -> SessionResponse | None:
        session = self.repository.get(session_id)
        if session is None:
            return None
        return SessionResponse.model_validate(session.to_dict())

    def advance_session(
        self,
        session_id: str,
        payload: SessionAdvanceRequest,
    ) -> SessionResponse | None:
        session = self.repository.get(session_id)
        if session is None:
            return None

        next_focus = self.prioritization_service.choose_next_focus(
            session.state_snapshot,
            payload.teacher_revision,
        )
        session.current_focus = next_focus
        session.guiding_questions = self.prioritization_service.default_questions(
            next_focus
        )
        session.latest_draft = (
            f"Draft placeholder for {next_focus.value}. "
            "This will later be generated by the LLM workflow."
        )
        session.state_snapshot.update(payload.state_patch)
        if payload.teacher_revision:
            session.state_snapshot["last_teacher_revision"] = payload.teacher_revision
        if payload.teacher_answers:
            session.state_snapshot["last_teacher_answers"] = payload.teacher_answers

        if session.cycle_stage == ResearchCycleStage.PLANNING:
            session.cycle_stage = ResearchCycleStage.ACTION
        elif session.cycle_stage == ResearchCycleStage.ACTION:
            session.cycle_stage = ResearchCycleStage.OBSERVATION
        elif session.cycle_stage == ResearchCycleStage.OBSERVATION:
            session.cycle_stage = ResearchCycleStage.REFLECTION
        else:
            session.cycle_stage = ResearchCycleStage.PLANNING

        self.repository.save(session)
        return SessionResponse.model_validate(session.to_dict())


orchestration_service = OrchestrationService()

